name: 💡 Feature Request
description: Suggest a new feature or enhancement for ARK4 Helper
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a new feature!
        Please provide as much detail as possible to help us understand your idea.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting your feature request.
      options:
        - label: I have searched existing issues to avoid creating duplicates
          required: true
        - label: This is a single feature (not multiple unrelated requests)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also thought about [...]
    validations:
      required: false

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Critical (I can't use the application without it)
        - High (Would significantly improve my experience)
        - Medium (Would be a nice addition)
        - Low (Just an idea I had)
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: What type of user would benefit from this feature?
      options:
        - All users
        - New users
        - Advanced users
        - Specific use case (describe below)
      multiple: true
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or mockups about the feature request here.
        
        Tip: You can attach images by dragging and dropping them into this field.
    validations:
      required: false 